### ISSUE TITLE
Error: No Chrome installations found.

### ISSUE THREAD

**Issue by 2lach** [andreasonny83/lighthouse-ci#59]
## G'Day @andreasonny83

First of all got big ❤️for lighthouse-ci and I think this is an awesome service when I just wanna do a quick audit with no fuss 👍 

However today when I ran it I got some strange results:
<img width="637" alt="screenshot error" src="https://user-images.githubusercontent.com/11457600/72218979-4087a800-3541-11ea-9ae8-a4d030679d59.png">

I ran some checks on my end, which looked alrite. I have chrome installed (both standard and canary) 😄 But of course there might be something I overlooked or something that's not working properly on your end.

Was wondering if you could point me in the right direction?

Have an awesome day!
/2lach

My specs:
<img width="719" alt="screenfetch" src="https://user-images.githubusercontent.com/11457600/72219092-65c8e600-3542-11ea-8f26-c8a27bfb6919.png">
also I don't know if it would matter, but I did make the mistake of upgrading to Catalina 😞

**Comment by andreasonny83** [comment]
@2lach, first of all, thanks for using Lighthouse-CI.

From the example you provided, I can see you're proving an invalid URL. The correct format should be `lighthouse-ci https://www.google.com`.

I just tested the given command on my machine where I'm also running Catalina, and everything looks working fine. I'm running Chrome Dev 71 so I believe it's safe to assume it's not an OS related issue.

If, using the correct url syntax doesn't help, can you give the Docker solution a try? There's a `demo` folder in this project, run `make demo` and see if that works.

Please, let me know the result so I can take action about this issue

**Comment by 2lach** [comment]
Sounds good 👍 'll get back to after I get the results from the Docker test

**Comment by 2lach** [comment]
Hey @andreasonny83 hope all is good! 
I did the demo and it failed 😢 

attached the output from the make test
[lighthouse-ci-demo-output.txt](https://github.com/andreasonny83/lighthouse-ci/files/4053051/lighthouse-ci-demo-log.txt)

**Comment by andreasonny83** [comment]
Thanks for the update. I'll have a deeper look as it seems something is missing with the docker configuration.
I'll reopen the issue for now and I'll let you know any progress on this

**Comment by andreasonny83** [comment]
Hi @2lach 
I fixed the Demo app and included a section to the Readme explaining how to use it:https://github.com/andreasonny83/lighthouse-ci#demo-app
Please, have a look and let me know if that works for you

Thanks

**Comment by 2lach** [comment]
Hey there @andreasonny83  hope all is well!

I ran the demo, and took it for a spin.

At the first run of `make demo` it didn't work 😞 (see attached log file)

However, since you have been such a cool guy. Some might even say you got the true open-source spirit 😉 I figured 'Hey what f*ck maybe I can return the favour. 
And so I found the very small bug and fixed it (attached the fix as well)
and the demo app works 👍 
 
[lighthouse-ci-demo.log](https://github.com/andreasonny83/lighthouse-ci/files/4150186/lighthouse-ci-demo.log)

Bugfix:
`~/lighthouse-ci/demo/Makefile`
```Makefile
.PHONY: default build run install dev

# Commands for local development
build:
	docker build --rm -t sonny/lighthouse-demo .

# <- This guy right here was missing
install: 
	docker run --rm -it -v ${PWD}:/demo sonny/lighthouse-demo npm install

run:
	docker run --rm -it -v ${PWD}:/demo sonny/lighthouse-demo npm start

dev:
	docker run -it --rm -v ${PWD}:/demo sonny/lighthouse-demo /bin/bash

demo: build run
```

**Comment by andreasonny83** [comment]
Thanks a lot for the feedback.
I had a look at your changes and, honestly, the npm install step is not required any more as I included that in the Dockerfile so the container should already come with the node modules pre-installed.
However, I pushed some refactoring to clean the Makefile. It might be possible that you were getting a cached (old) version of the image when running the script where the `npm install` step was not included. You can manually delete the image and run `make demo` again.
A part from that configuration, did you manage to solve your initial problem with Chrome?

**Comment by 2lach** [comment]
Hey there

Right you are, I believe the cached version was the one I used in the previous demo run.
Cause now (after docker cleaned, cloned repo, new `make demo`) it works just as it should 👍 
 
But in regards to the original issue. I just don't see what might be causing it. 
I still have the same "No chrome installation found" error. 

I've removed and reinstalled lighthouse-ci, verified even did a total clean of the npm cache, changed node versions. 
I even spun up a vm and tried it there and still I get the same issue. 
From what i gather it's only me that having this issue, which means it's local...

So even though it really sucks and you been a good sport all the way! + I got nothing but ❤️4 lighthouse-ci.

But I feel like it's eating up too much time (for both of us) so for now I think the best move is to close this issue and if the same issue resurfaces for somebody else it might be worth having a new look. 

Of course if I find the reason, I'll let you know what it was. 

Have a good one
2lach
